parser: babel-eslint
parserOptions:
  ecmaVersion: 12
extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  es6: true
  node: true
  jasmine: true
plugins:
  - prettier
rules:
  prettier/prettier: error
  no-unused-vars:
    - error
    - argsIgnorePattern: next
